use sakila;
-- list the number of films per category
select * from film;
select * from film_category;
select * from category; 

SELECT 
    name, COUNT(f.film_id)
FROM
    film AS f
        JOIN
    film_category AS fc ON f.film_id = fc.film_id
        LEFT JOIN
    category AS c ON fc.category_id = c.category_id
GROUP BY c.name; 


-- Retrieve the store ID, city, and country for each store.

select * from store; 
select * from address; 
select * from city; 
select * from country; 

select s.store_id, c.city, country.country from store as s
left join address as a
on s.address_id = a.address_id
left join city as c
on a.city_id = c.city_id
left join country 
on c.country_id = country.country_id;

-- Calculate the total revenue generated by each store in dollars.

select * from payment;
select * from customer;

select c.store_id, sum(p.amount) as total_revenue from customer as c
left join payment as p
on c.customer_id  = p.customer_id
group by c.store_id;

-- Determine the average running time of films for each category

SELECT 
    name, ROUND(AVG(f.length),2)
FROM
    film AS f
        JOIN
    film_category AS fc ON f.film_id = fc.film_id
        LEFT JOIN
    category AS c ON fc.category_id = c.category_id
group by name;
 
-- Identify the film categories with the longest average running time.

select * from film;
SELECT 
    c.name, AVG(f.length) as average_length
FROM
    film AS f
        JOIN
    film_category AS fc ON f.film_id = fc.film_id
        LEFT JOIN
    category AS c ON fc.category_id = c.category_id
group by c.name
order by average_length DESC limit 1;

-- Display the top 10 most frequently rented movies in descending order.



-- Determine if "Academy Dinosaur" can be rented from Store 1.

-- Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.'
--  Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."

